"""Add AI metadata to meeting_logs

Revision ID: 21cd742d6b44
Revises: 634b5374c2d2
Create Date: 2025-08-01 14:24:19.434713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21cd742d6b44'
down_revision: Union[str, Sequence[str], None] = '634b5374c2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('participant_user_id', sa.Integer(), nullable=False),
    sa.Column('coaching_category', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_logs.meeting_id'], ),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meeting_logs', sa.Column('subsidiary', sa.String(), nullable=True))
    op.add_column('meeting_logs', sa.Column('department', sa.String(), nullable=True))
    op.add_column('meeting_logs', sa.Column('meeting_type', sa.String(), nullable=True))
    op.add_column('meeting_logs', sa.Column('meeting_subtype', sa.String(), nullable=True))
    op.add_column('meeting_logs', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('meeting_logs', sa.Column('key_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('meeting_logs', sa.Column('enriched_output_path', sa.Text(), nullable=True))
    op.create_index(op.f('ix_meeting_logs_created_at'), 'meeting_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_logs_created_at'), table_name='meeting_logs')
    op.drop_column('meeting_logs', 'enriched_output_path')
    op.drop_column('meeting_logs', 'key_decisions')
    op.drop_column('meeting_logs', 'tags')
    op.drop_column('meeting_logs', 'meeting_subtype')
    op.drop_column('meeting_logs', 'meeting_type')
    op.drop_column('meeting_logs', 'department')
    op.drop_column('meeting_logs', 'subsidiary')
    op.drop_table('training_queue')
    # ### end Alembic commands ###
