"""Create baseline models from existing schema

Revision ID: 634b5374c2d2
Revises: 
Create Date: 2025-07-31 12:51:15.516278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634b5374c2d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('participant_user_id', sa.Integer(), nullable=False),
    sa.Column('coaching_category', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_logs.meeting_id'], ),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_logs_created_at'), 'meeting_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_logs_created_at'), table_name='meeting_logs')
    op.drop_table('training_queue')
    # ### end Alembic commands ###
