"""Add voice_profile_id to users table

Revision ID: 887b418b06fd
Revises: 21cd742d6b44
Create Date: 2025-08-04 09:58:05.717001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887b418b06fd'
down_revision: Union[str, Sequence[str], None] = '21cd742d6b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('voice_profile_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['voice_profile_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'voice_profile_id')
    # ### end Alembic commands ###
