name: Build and Deploy Meeting Tool to Azure Container App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: meeting-tool

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 🏷️ Define dynamic image tag
        id: set-tag
        run: echo "TAG=build-$(date +%s)" >> $GITHUB_ENV

      - name: 🏗️ Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/$IMAGE_NAME:$TAG .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/$IMAGE_NAME:$TAG

      - name: 🔐 Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🚀 Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/$IMAGE_NAME:$TAG
          containerAppName: ${{ secrets.AZURE_CONTAINERAPP_NAME }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
