name: Build and Deploy Legal GPT Chatbot to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Pull previous image for cache (optional)
        run: |
          docker pull ${{ secrets.ACR_LOGIN_SERVER }}/meeting-tool:latest || true

      - name: Build and push Docker image with cache
        run: |
          docker build \
            --cache-from ${{ secrets.ACR_LOGIN_SERVER }}/meeting-tool:latest \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/meeting-tool:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/meeting-tool:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/meeting-tool:latest